import 'package:flutter/material.dart';

import 'package:common/src/theme/muuvie_colors.dart';

abstract final class MuuvieColorScheme {
  static const ColorScheme light = ColorScheme(
    brightness: Brightness.light,
    primary: MuuvieColors.primary,
    onPrimary: MuuvieColors.neutral,
    primaryContainer: MuuvieColors.primaryContainer,
    onPrimaryContainer: MuuvieColors.onPrimaryContainer,
    secondary: MuuvieColors.secondary,
    onSecondary: MuuvieColors.primary,
    secondaryContainer: MuuvieColors.secondaryContainer,
    onSecondaryContainer: MuuvieColors.onSecondaryContainer,
    tertiary: MuuvieColors.tertiary,
    onTertiary: MuuvieColors.primary,
    tertiaryContainer: MuuvieColors.tertiaryContainer,
    onTertiaryContainer: MuuvieColors.onTertiaryContainer,
    error: MuuvieColors.error,
    onError: MuuvieColors.onError,
    errorContainer: MuuvieColors.errorContainer,
    onErrorContainer: MuuvieColors.onErrorContainer,
    surface: MuuvieColors.surfaceLight,
    onSurface: MuuvieColors.onSurfaceLight,
    surfaceContainerHighest: MuuvieColors.surfaceVariantLight,
    onSurfaceVariant: MuuvieColors.onSurfaceVariantLight,
    outline: MuuvieColors.outlineLight,
    outlineVariant: MuuvieColors.outlineVariantLight,
    shadow: MuuvieColors.shadow,
    scrim: MuuvieColors.scrim,
    inverseSurface: MuuvieColors.inverseSurfaceLight,
    onInverseSurface: MuuvieColors.inverseOnSurfaceLight,
    inversePrimary: MuuvieColors.inversePrimaryLight,
    surfaceContainerLow: MuuvieColors.surfaceContainerLight,
  );

  static const ColorScheme dark = ColorScheme(
    brightness: Brightness.dark,
    primary: MuuvieColors.inversePrimaryLight,
    onPrimary: MuuvieColors.primaryDark,
    primaryContainer: MuuvieColors.primaryLight,
    onPrimaryContainer: MuuvieColors.onPrimaryContainer,
    secondary: MuuvieColors.secondary,
    onSecondary: MuuvieColors.secondaryDark,
    secondaryContainer: MuuvieColors.secondaryContainerDark,
    onSecondaryContainer: MuuvieColors.onSecondaryContainerDark,
    tertiary: MuuvieColors.tertiary,
    onTertiary: MuuvieColors.tertiaryDark,
    tertiaryContainer: MuuvieColors.tertiaryContainerDark,
    onTertiaryContainer: MuuvieColors.onTertiaryContainerDark,
    error: MuuvieColors.errorDark,
    onError: MuuvieColors.onErrorDark,
    errorContainer: MuuvieColors.errorContainerDark,
    onErrorContainer: MuuvieColors.onErrorContainerDark,
    surface: MuuvieColors.surfaceDark,
    onSurface: MuuvieColors.onSurfaceDark,
    surfaceContainerHighest: MuuvieColors.surfaceVariantDark,
    onSurfaceVariant: MuuvieColors.onSurfaceVariantDark,
    outline: MuuvieColors.outlineDark,
    outlineVariant: MuuvieColors.outlineVariantDark,
    shadow: MuuvieColors.shadow,
    scrim: MuuvieColors.scrim,
    inverseSurface: MuuvieColors.inverseSurfaceDark,
    onInverseSurface: MuuvieColors.inverseOnSurfaceDark,
    inversePrimary: MuuvieColors.inversePrimaryDark,
    surfaceContainerLow: MuuvieColors.surfaceContainerDark,
  );
}